version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/yaong:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: ${REDIS_HOST} # 외부 Redis 호스트
      SPRING_REDIS_PORT: 6379
    depends_on: [] # Redis 의존성 제거
