spring.application.name=yaong
#logging.level.root=TRACE
#logging.level.org.springframework.security=TRACE
#logging.level.com.khu.yaong=TRACE
spring.config.import=classpath:application-auth.properties
